### PR TITLE
Same class name multiple times - refactored

### PR DESCRIPTION
**Pull request by jembezmamy**
Ok, so here I've created a `body-class` service that manages global class names list. I had to rearrange tests since `set-body-class` component doesn't have the same responsibility anymore. But I saved some test cases in an acceptance test.

### CODE REVIEW

**Comment by ef4** [comment]
Thanks for working on this.

It appears to break fastboot support. 

And a test is failing on Ember 2.8, but I think that is only because of the way the test is written. `factoryFor` is not available in older versions. You can use the older private equivalent which is `_lookupFactory`. In general this test will be less fragile if it's switches to a rendering test that actually renders templates, rather than manually `create`ing components, which is a thing that apps never do.

**Comment by jembezmamy** [comment]
Aah, ok, now I noticed ember-try in this addon. I fixed both things and now tests are passed in all scenarios.

**Comment by ef4** [comment]
Nice, thanks.

**Comment by ef4** [comment]
Published 0.4.1.

**Pull request merged**
